# Generated by Django 5.1.4 on 2025-10-10 15:33

import autoslug.fields
import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'News Categories',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('summary', models.TextField(blank=True, help_text='A short summary of the news article', null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('author', models.CharField(blank=True, max_length=100)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/featured/')),
                ('is_trending', models.BooleanField(default=False, help_text='Flag if the article is trending')),
                ('is_breaking', models.BooleanField(default=False, help_text='Flag if the article is breaking news')),
                ('is_latest', models.BooleanField(default=False, help_text='Flag if the article is among the latest')),
                ('is_exclusive', models.BooleanField(default=False, help_text='Flag if the article is exclusive content')),
                ('is_mount_everest_south', models.BooleanField(default=False, help_text='Flag if the article is exclusive content')),
                ('is_mount_everest_north', models.BooleanField(default=False, help_text='Flag if the article is exclusive content')),
                ('location', models.CharField(blank=True, help_text='Location of the event', max_length=100, null=True)),
                ('peak_altitude', models.IntegerField(blank=True, help_text='Peak altitude in meters', null=True)),
                ('weather_update', models.CharField(blank=True, help_text='Latest weather conditions', max_length=255, null=True)),
                ('expedition_info', models.TextField(blank=True, help_text='Details about the expedition or climbing team', null=True)),
                ('risk_level', models.CharField(blank=True, help_text='Risk level (e.g., Low, Moderate, High)', max_length=50, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for search and filtering', max_length=255, null=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('likes', models.PositiveIntegerField(default=0, help_text='Number of likes')),
                ('shares', models.PositiveIntegerField(default=0, help_text='Number of shares')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.newscategory')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_images', to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='news.newscategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_subcategories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News SubCategory',
                'verbose_name_plural': 'News SubCategories',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='news',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.newssubcategory'),
        ),
        migrations.CreateModel(
            name='NewsVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='news/videos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_videos', to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='news.news')),
            ],
        ),
    ]
