# Generated by Django 5.1.6 on 2025-10-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailnewsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnewsletter',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='emailnewsletter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
