# Generated by Django 5.1.6 on 2025-10-12 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='new', max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField()),
                ('budget', models.CharField(choices=[('500-2000', '$500 - $2,000'), ('2000-5000', '$2,000 - $5,000'), ('5000-10000', '$5,000 - $10,000'), ('10000+', '$10,000+')], max_length=20)),
                ('channels', models.CharField(help_text='Comma-separated advertising channels', max_length=100)),
                ('message', models.TextField()),
                ('marketing_materials', models.ImageField(blank=True, null=True, upload_to='advertising/materials/')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('homepage', 'Homepage'), ('south', 'Mount Everest South'), ('north', 'Mount Everest North')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('url_destination', models.URLField(help_text='Destination URL for the ad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ads_created_by', models.ForeignKey(blank=True, help_text='Linked user if authenticated', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertising_channel.advertisinginquiry')),
            ],
        ),
    ]
