# Generated by Django 5.1.6 on 2025-10-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising_channel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adplacement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='adplacement',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='adplacement',
            name='url_destination',
        ),
    ]
