# Generated by Django 5.1.6 on 2025-10-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising_channel', '0002_remove_adplacement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisinginquiry',
            name='marketing_materials',
            field=models.FileField(blank=True, null=True, upload_to='advertising/materials/'),
        ),
    ]
