# Generated by Django 5.1.6 on 2025-10-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('AGENT', 'Agent'), ('USER', 'User'), ('INVESTOR', 'Investor'), ('INTERNAL', 'Internal')], default='USER', max_length=10, verbose_name='User Type'),
        ),
    ]
