# Generated by Django 5.1.6 on 2025-10-13 11:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('parameters', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('successful', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('elevation', models.IntegerField(help_text='Elevation in meters')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tavg', models.DecimalField(decimal_places=2, help_text='Average temperature in Celsius', max_digits=5)),
                ('tmin', models.DecimalField(decimal_places=2, help_text='Average minimum temperature in Celsius', max_digits=5)),
                ('tmax', models.DecimalField(decimal_places=2, help_text='Average maximum temperature in Celsius', max_digits=5)),
                ('prcp', models.DecimalField(decimal_places=3, help_text='Total precipitation in mm', max_digits=6)),
                ('wspd', models.DecimalField(blank=True, decimal_places=2, help_text='Average wind speed in km/h', max_digits=6, null=True)),
                ('pres', models.DecimalField(blank=True, decimal_places=2, help_text='Average air pressure in hPa', max_digits=7, null=True)),
                ('tsun', models.IntegerField(blank=True, help_text='Total sunshine duration in minutes', null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.weatherstation')),
            ],
            options={
                'indexes': [models.Index(fields=['station', 'date'], name='weather_mon_station_4964d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='HourlyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('temp', models.DecimalField(decimal_places=2, help_text='Temperature in Celsius', max_digits=5)),
                ('dwpt', models.DecimalField(decimal_places=2, help_text='Dew point in Celsius', max_digits=5)),
                ('rhum', models.IntegerField(help_text='Relative humidity in percent', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('prcp', models.DecimalField(decimal_places=3, help_text='Precipitation in mm', max_digits=6)),
                ('snow', models.IntegerField(blank=True, help_text='Snow depth in mm', null=True)),
                ('wdir', models.IntegerField(blank=True, help_text='Wind direction in degrees', null=True)),
                ('wspd', models.DecimalField(decimal_places=2, help_text='Wind speed in km/h', max_digits=6)),
                ('wpgt', models.DecimalField(blank=True, decimal_places=2, help_text='Peak wind gust in km/h', max_digits=6, null=True)),
                ('pres', models.DecimalField(decimal_places=2, help_text='Air pressure in hPa', max_digits=7)),
                ('tsun', models.IntegerField(blank=True, help_text='Sunshine duration in minutes', null=True)),
                ('coco', models.IntegerField(blank=True, help_text='Weather condition code', null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.weatherstation')),
            ],
            options={
                'indexes': [models.Index(fields=['station', 'time'], name='weather_hou_station_86ba62_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tavg', models.DecimalField(decimal_places=2, help_text='Average temperature in Celsius', max_digits=5)),
                ('tmin', models.DecimalField(decimal_places=2, help_text='Minimum temperature in Celsius', max_digits=5)),
                ('tmax', models.DecimalField(decimal_places=2, help_text='Maximum temperature in Celsius', max_digits=5)),
                ('prcp', models.DecimalField(decimal_places=3, help_text='Precipitation in mm', max_digits=6)),
                ('snow', models.IntegerField(blank=True, help_text='Snow depth in mm', null=True)),
                ('wdir', models.IntegerField(blank=True, help_text='Wind direction in degrees', null=True)),
                ('wspd', models.DecimalField(blank=True, decimal_places=2, help_text='Average wind speed in km/h', max_digits=6, null=True)),
                ('wpgt', models.DecimalField(blank=True, decimal_places=2, help_text='Peak wind gust in km/h', max_digits=6, null=True)),
                ('pres', models.DecimalField(blank=True, decimal_places=2, help_text='Air pressure in hPa', max_digits=7, null=True)),
                ('tsun', models.IntegerField(blank=True, help_text='Sunshine duration in minutes', null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.weatherstation')),
            ],
            options={
                'indexes': [models.Index(fields=['station', 'date'], name='weather_dai_station_84c3bd_idx')],
            },
        ),
    ]
