# Generated by Django 5.1.6 on 2025-10-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatheranalysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiCallLog',
        ),
        migrations.RemoveField(
            model_name='dailyweather',
            name='station',
        ),
        migrations.RemoveField(
            model_name='hourlyweather',
            name='station',
        ),
        migrations.RemoveField(
            model_name='monthlyweather',
            name='station',
        ),
        migrations.DeleteModel(
            name='WeatherAnalysis',
        ),
        migrations.DeleteModel(
            name='DailyWeather',
        ),
        migrations.DeleteModel(
            name='HourlyWeather',
        ),
        migrations.DeleteModel(
            name='MonthlyWeather',
        ),
        migrations.DeleteModel(
            name='WeatherStation',
        ),
    ]
